"""update in subscription table

Revision ID: 2d88290b0bf9
Revises: 4c7eb183ff7b
Create Date: 2025-05-12 16:56:34.555272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d88290b0bf9'
down_revision: Union[str, None] = '4c7eb183ff7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscriptions', 'time_used',
               existing_type=mysql.TIME(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'00:00:00'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscriptions', 'time_used',
               existing_type=sa.Integer(),
               type_=mysql.TIME(),
               existing_nullable=False,
               existing_server_default=sa.text("'00:00:00'"))
    # ### end Alembic commands ###
