"""update in indusry table

Revision ID: 35ba012f4ebc
Revises: 6eb0d88d5e42
Create Date: 2025-05-22 13:13:24.142336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ba012f4ebc'
down_revision: Union[str, None] = '6eb0d88d5e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industries', sa.Column('details', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('industries', 'details')
    # ### end Alembic commands ###
