"""update in session 1 table

Revision ID: 3d86d0a46c2d
Revises: 6659efd22ee0
Create Date: 2025-05-15 14:42:23.818028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '3d86d0a46c2d'
down_revision: Union[str, None] = '6659efd22ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sessions',
        'duration',
        existing_type=mysql.INTEGER(),
        nullable=True,
        server_default=0
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sessions',
        'duration',
        existing_type=mysql.Integer(),
        nullable=True,
        server_default=None
    )
    # ### end Alembic commands ###