"""new updates

Revision ID: 40d12d056389
Revises: 3d86d0a46c2d
Create Date: 2025-05-20 16:31:17.801873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40d12d056389'
down_revision: Union[str, None] = '3d86d0a46c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_mode_manufacturing_model', table_name='interaction_mode_manufacturing_models')
    op.drop_table('interaction_mode_manufacturing_models')
    op.drop_index('uq_mode_plant_size_impact', table_name='interaction_mode_plant_size_impacts')
    op.drop_table('interaction_mode_plant_size_impacts')
    op.drop_index('uq_mode_ai_role', table_name='interaction_mode_ai_roles')
    op.drop_table('interaction_mode_ai_roles')
    op.add_column('sessions', sa.Column('ai_persona', mysql.JSON(), nullable=False))
    op.alter_column('sessions', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint('sessions_ibfk_2', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'persona_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('persona_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key('sessions_ibfk_2', 'sessions', 'ai_personas', ['persona_id'], ['persona_id'])
    op.alter_column('sessions', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_column('sessions', 'ai_persona')
    op.create_table('interaction_mode_ai_roles',
    sa.Column('interaction_mode_ai_role_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('mode_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('ai_role', mysql.ENUM('quality_manager', 'production_manager', 'maintenance_manager', 'plant_manager'), nullable=False),
    sa.Column('prompt_template', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['interaction_modes.mode_id'], name='interaction_mode_ai_roles_ibfk_1'),
    sa.PrimaryKeyConstraint('interaction_mode_ai_role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_mode_ai_role', 'interaction_mode_ai_roles', ['mode_id', 'ai_role'], unique=True)
    op.create_table('interaction_mode_plant_size_impacts',
    sa.Column('interaction_mode_plant_size_impact_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('mode_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('plant_size_impact', mysql.ENUM('small', 'medium', 'large'), nullable=False),
    sa.Column('prompt_template', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['interaction_modes.mode_id'], name='interaction_mode_plant_size_impacts_ibfk_1'),
    sa.PrimaryKeyConstraint('interaction_mode_plant_size_impact_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_mode_plant_size_impact', 'interaction_mode_plant_size_impacts', ['mode_id', 'plant_size_impact'], unique=True)
    op.create_table('interaction_mode_manufacturing_models',
    sa.Column('interaction_mode_manufacturing_model_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('mode_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('manufacturing_model', mysql.ENUM('self_manufacturing', 'contract_manufacturing'), nullable=False),
    sa.Column('prompt_template', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['interaction_modes.mode_id'], name='interaction_mode_manufacturing_models_ibfk_1'),
    sa.PrimaryKeyConstraint('interaction_mode_manufacturing_model_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_mode_manufacturing_model', 'interaction_mode_manufacturing_models', ['mode_id', 'manufacturing_model'], unique=True)
    # ### end Alembic commands ###
