"""new changes

Revision ID: 4d687e47d3d9
Revises: 8c773d2322ec
Create Date: 2025-06-04 13:10:36.776709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d687e47d3d9'
down_revision: Union[str, None] = '8c773d2322ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""


    # Drop FKs and index for interaction_mode_plant_size_impacts


    # The rest of your migration

    op.add_column('ai_roles', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('manufacturing_models', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('plant_size_impacts', sa.Column('description', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_size_impacts', 'description')
    op.drop_column('manufacturing_models', 'description')
    op.drop_column('ai_roles', 'description')
    op.create_index('ix_ai_persona_lookup', 'ai_personas', ['industry_id', 'ai_role_id', 'experience_level', 'geography', 'plant_size_impact_id', 'manufacturing_model_id'], unique=False, mysql_length={'geography': 255})
    op.create_table('interaction_mode_manufacturing_models',
    sa.Column('interaction_mode_manufacturing_model_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('mode_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('manufacturing_model_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('prompt_template', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturing_model_id'], ['manufacturing_models.manufacturing_model_id'], name='interaction_mode_manufacturing_models_ibfk_2'),
    sa.ForeignKeyConstraint(['mode_id'], ['interaction_modes.mode_id'], name='interaction_mode_manufacturing_models_ibfk_1'),
    sa.PrimaryKeyConstraint('interaction_mode_manufacturing_model_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_mode_manufacturing_model', 'interaction_mode_manufacturing_models', ['mode_id', 'manufacturing_model_id'], unique=True)
    op.create_table('interaction_mode_plant_size_impacts',
    sa.Column('interaction_mode_plant_size_impact_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('mode_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('plant_size_impact_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('prompt_template', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['interaction_modes.mode_id'], name='interaction_mode_plant_size_impacts_ibfk_1'),
    sa.ForeignKeyConstraint(['plant_size_impact_id'], ['plant_size_impacts.plant_size_impact_id'], name='interaction_mode_plant_size_impacts_ibfk_2'),
    sa.PrimaryKeyConstraint('interaction_mode_plant_size_impact_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_mode_plant_size_impact', 'interaction_mode_plant_size_impacts', ['mode_id', 'plant_size_impact_id'], unique=True)
    op.create_table('interaction_mode_ai_roles',
    sa.Column('interaction_mode_ai_role_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('mode_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('ai_role_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('prompt_template', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['ai_role_id'], ['ai_roles.ai_role_id'], name='interaction_mode_ai_roles_ibfk_2'),
    sa.ForeignKeyConstraint(['mode_id'], ['interaction_modes.mode_id'], name='interaction_mode_ai_roles_ibfk_1'),
    sa.PrimaryKeyConstraint('interaction_mode_ai_role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uq_mode_ai_role', 'interaction_mode_ai_roles', ['mode_id', 'ai_role_id'], unique=True)
    op.create_table('performance_reports',
    sa.Column('report_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('overall_score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('communication_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('objection_handling', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('adaptability', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('persuasiveness', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_interest', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale_closing', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discovery', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cross_selling', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('solution_fit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coaching_summary', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name='performance_reports_ibfk_1'),
    sa.PrimaryKeyConstraint('report_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
