"""update in session table

Revision ID: 63ec1d5e94b9
Revises: 
Create Date: 2025-05-15 13:20:29.719445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63ec1d5e94b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_personas', sa.Column('plant_size_impact', sa.Enum('small', 'medium', 'large', name='plant_size_impact_enum'), nullable=True, comment='Plant Size Impact: small (<50 employees): Cash flow sensitivity, resource constraints, downtime impact, expedited decisions; medium (50-200): Balanced cost/capability concerns, department approvals, scalability focus; large (>200): Complex approval process, enterprise standards, formal documentation, corporate alignment'))
    op.alter_column('ai_personas', 'role',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('quality_manager', 'production_manager', 'maintenance_manager', 'plant_manager', name='role_enum'),
               existing_nullable=True)
    op.drop_column('ai_personas', 'interview_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_personas', sa.Column('interview_results', mysql.TEXT(), nullable=True))
    op.alter_column('ai_personas', 'role',
               existing_type=sa.Enum('quality_manager', 'production_manager', 'maintenance_manager', 'plant_manager', name='role_enum'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('ai_personas', 'plant_size_impact')
    # ### end Alembic commands ###
