"""update in session table

Revision ID: 6659efd22ee0
Revises: d9dcb59355a7
Create Date: 2025-05-15 14:38:29.618432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6659efd22ee0'
down_revision: Union[str, None] = 'd9dcb59355a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
