"""update in intraction mode table

Revision ID: 6eb0d88d5e42
Revises: 
Create Date: 2025-05-21 16:49:09.715173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6eb0d88d5e42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_ai_persona_lookup', 'ai_personas', ['industry_id', 'ai_role_id', 'experience_level', 'geography', 'plant_size_impact_id', 'manufacturing_model_id'], unique=False, mysql_length={'geography': 255})
    op.create_index(
        'uq_ai_persona_unique_combo',
        'ai_personas',
        ['name', 'industry_id', 'ai_role_id', 'experience_level', 'geography', 'plant_size_impact_id', 'manufacturing_model_id'],
        unique=True,
        mysql_length={'geography': 255}
    )
    op.alter_column('interaction_modes', 'name',
               existing_type=mysql.ENUM('prospecting', 'sales', 'closing'),
               type_=sa.Enum('prospecting', 'discovering', 'closing', name='interaction_mode_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interaction_modes', 'name',
               existing_type=sa.Enum('prospecting', 'descovering', 'closing', name='interaction_mode_enum'),
               type_=mysql.ENUM('prospecting', 'sales', 'closing'),
               existing_nullable=False)
    op.drop_index('uq_ai_persona_unique_combo', table_name='ai_personas')
    # op.drop_index('ix_ai_persona_lookup', table_name='ai_personas', mysql_length={'geography': 255})
    # ### end Alembic commands ###
