"""update in user table

Revision ID: 7108fcc86968
Revises: 
Create Date: 2025-05-10 17:17:03.759349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7108fcc86968'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'subscriptions', ['subscription_id'], ['subscription_id'])
    op.drop_column('users', 'access_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_level', mysql.ENUM('free_trial', 'single_session', 'subscription', 'enterprise'), server_default=sa.text("'free_trial'"), nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
