"""this new generated revision

Revision ID: 80eb01d3a995
Revises: e00dcabf6521
Create Date: 2025-06-17 12:42:07.879193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80eb01d3a995'
down_revision: Union[str, None] = 'e00dcabf6521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_personas', sa.Column('company_size_id', sa.String(length=36), nullable=False))

    op.create_foreign_key(None, 'ai_personas', 'company_size', ['company_size_id'], ['company_size_id'])
    op.alter_column('produced_product_category', 'details',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.create_table(
        'persona_produced_product',
        sa.Column('persona_product_id', sa.String(length=36), primary_key=True, nullable=False),
        sa.Column('persona_id', sa.String(length=36), sa.ForeignKey('ai_personas.persona_id'), nullable=False),
        sa.Column('product_id', sa.String(length=36), sa.ForeignKey('produced_product_category.product_id'), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produced_product_category', 'details',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'ai_personas', type_='foreignkey')
    op.drop_constraint('uq_ai_persona_unique_combo', 'ai_personas', type_='unique')
    op.create_index('ix_ai_persona_lookup', 'ai_personas', ['industry_id', 'ai_role_id', 'geography', 'plant_size_impact_id', 'manufacturing_model_id'], unique=False, mysql_length={'geography': 255})
    op.drop_column('ai_personas', 'company_size_id')
    op.drop_table('persona_produced_product')
    # ### end Alembic commands ###
