"""update in ai session table and add tables

Revision ID: 8c773d2322ec
Revises: dd71c3c26e62
Create Date: 2025-05-27 15:12:01.496540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c773d2322ec'
down_revision: Union[str, None] = 'dd71c3c26e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('performance_report', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'performance_report')
    # ### end Alembic commands ###
