"""update in different tables

Revision ID: a55446e3b46d
Revises: 0e5619015fb5
Create Date: 2025-05-12 15:02:09.127253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a55446e3b46d'
down_revision: Union[str, None] = '0e5619015fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'max_session_duration',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'max_session_duration',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
