"""update in different tables

Revision ID: aa5e2e7f97b6
Revises: f51c47225092
Create Date: 2025-05-11 00:41:23.687162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa5e2e7f97b6'
down_revision: Union[str, None] = 'f51c47225092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('sales_person', 'manager', 'admin', 'super_admin', name='role_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.Enum('sales_person', 'manager', 'admin', 'super_admin', name='role_enum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
