"""new changes 2

Revision ID: db487110cf14
Revises: 4d687e47d3d9
Create Date: 2025-06-06 13:06:27.704717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db487110cf14'
down_revision: Union[str, None] = '4d687e47d3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('ai_personas', 'geography',
               existing_type=mysql.TEXT(),
               nullable=False)

    op.drop_column('ai_personas', 'behavioral_traits')
    op.alter_column('ai_roles', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('manufacturing_models', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('plant_size_impacts', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_size_impacts', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('manufacturing_models', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ai_roles', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('ai_personas', sa.Column('behavioral_traits', mysql.JSON(), nullable=True))
    op.create_index('ix_ai_persona_lookup', 'ai_personas', ['industry_id', 'ai_role_id', 'experience_level', 'geography', 'plant_size_impact_id', 'manufacturing_model_id'], unique=False, mysql_length={'geography': 255})
    op.alter_column('ai_personas', 'geography',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('ai_personas', 'behavioral_detail')
    # ### end Alembic commands ###
