"""update ai_persona table

Revision ID: df4ba598ff96
Revises: aa5e2e7f97b6
Create Date: 2025-05-11 21:58:53.092665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df4ba598ff96'
down_revision: Union[str, None] = 'aa5e2e7f97b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_personas', sa.Column('experience_level', sa.Enum('junior', 'mid', 'senior', 'executive', name='experience_level_enum'), nullable=True))
    op.add_column('ai_personas', sa.Column('geography', sa.Text(), nullable=True))
    op.alter_column('ai_personas', 'behavioral_traits',
               existing_type=mysql.TEXT(),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.alter_column('interaction_modes', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('prospecting', 'sales', 'closing', name='interaction_mode_enum'),
               existing_nullable=False)
    op.add_column('users', sa.Column('status_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('users', 'role_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('users', 'subscription_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscription_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('users', 'role_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_column('users', 'status_active')
    op.alter_column('interaction_modes', 'name',
               existing_type=sa.Enum('prospecting', 'sales', 'closing', name='interaction_mode_enum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('ai_personas', 'behavioral_traits',
               existing_type=mysql.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_column('ai_personas', 'geography')
    op.drop_column('ai_personas', 'experience_level')
    # ### end Alembic commands ###
