"""this is new change

Revision ID: e00dcabf6521
Revises: 
Create Date: 2025-06-12 17:02:51.888086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e00dcabf6521'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###



    op.drop_column('ai_personas', 'experience_level')
    op.alter_column('interaction_modes', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
  
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_size_impacts', sa.Column('description', mysql.TEXT(), nullable=False))
    op.alter_column('interaction_modes', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.add_column('ai_personas', sa.Column('experience_level', mysql.ENUM('junior', 'mid', 'senior'), nullable=False))
    op.drop_constraint('uq_ai_persona_unique_combo', 'ai_personas', type_='unique')
    op.create_unique_constraint('uq_ai_persona_unique_combo', 'ai_personas', ['name', 'industry_id', 'ai_role_id', 'experience_level', 'geography', 'plant_size_impact_id', 'manufacturing_model_id'])
    op.create_index('ix_ai_persona_lookup', 'ai_personas', ['industry_id', 'ai_role_id', 'experience_level', 'geography', 'plant_size_impact_id', 'manufacturing_model_id'], unique=False, mysql_length={'geography': 255})
    op.drop_column('ai_personas', 'profile_pic')
    # ### end Alembic commands ###
