"""update in different tables

Revision ID: f51c47225092
Revises: 7108fcc86968
Create Date: 2025-05-11 00:14:35.687364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f51c47225092'
down_revision: Union[str, None] = '7108fcc86968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_personas', sa.Column('status_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('interaction_modes', sa.Column('status_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('roles', sa.Column('status_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('roles', 'name',
               existing_type=mysql.ENUM('sales_person', 'manager', 'admin', 'super_admin'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('sessions', 'duration',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('subscriptions', sa.Column('status_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_column('subscriptions', 'payment_status')
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'otp_code',
               existing_type=mysql.VARCHAR(length=6),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp_code',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('subscriptions', sa.Column('payment_status', mysql.ENUM('pending', 'paid', 'cancelled'), nullable=False))
    op.drop_column('subscriptions', 'status_active')
    op.alter_column('sessions', 'duration',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('sales_person', 'manager', 'admin', 'super_admin'),
               existing_nullable=False)
    op.drop_column('roles', 'status_active')
    op.drop_column('interaction_modes', 'status_active')
    op.drop_column('ai_personas', 'status_active')
    # ### end Alembic commands ###
